### ISSUE TITLE
Provádět kontrolu stavu členského účtu při odhlášení z oddílu

### ISSUE THREAD

**Issue by dapolach** [zabiny/klabis#9]
# Kontrola stavu účtu člena při jeho odhlášce z oddílu

## Akceptační podmínky

- znemožnit odhlášku / důrazně upozornit na nenulový stav účtu člena při pokusu o jeho odhlášení

## Související tickety

#14 - "Rušení" členů oddílu na základě obdržené odhlášky

**Comment by otahirs** [comment]
zavřeno ve prospěch [#14](https://github.com/zabiny/klabis/issues/14)
